### ISSUE TITLE
darktable doesn't render any fonts

### ISSUE THREAD

**Issue by webmind** [sergiusens/darktable-snap#15]
When installing darktable via snap, all letters are represented by blocks. 

Trying to install darktable 2.4.4snap1 on
snap    2.35
snapd   2.35
series  16
debian  9
kernel  4.9.0-8-amd64

Looks like this:

![darktable-snap](https://user-images.githubusercontent.com/400804/46337620-3f718680-c62e-11e8-8c1f-8a27afba8a0c.png)

**Comment by sergiusens** [comment]
This should no longer be a problem with the latest changes to the snap to use a system isolated font cache, please reopen if this occurs again.
