### ISSUE TITLE
Cannot Import Folder that is a Samba Share

### ISSUE THREAD

**Issue by borgmanJeremy** [sergiusens/darktable-snap#37]
Hello,

My photos are stored on a NAS and shared via samba. I mounted the samba share to /mnt/photos. I am able to access this folder with the apt version of Darktable but not the snap so I suspect there is a confinement issue.

**Comment by sergiusens** [comment]
Darktable snap plugs removable-media, this should work, but access to /mnt requires snapd version 2.36+.

https://snapcraft.io/docs/removable-media-interface

Please reopen if the issue is still there
