### ISSUE TITLE
Update to 3.6?

### ISSUE THREAD

**Issue by danrobinson78** [sergiusens/darktable-snap#39]
Noticed 3.6.1 has been out and it's not in edge yet.

I'd send a PR but I assume this is trivial for someone that knows how Snap works so it's probably faster for someone to update than to tell me I screwed up because I'd be trying to learn Snap recipes at the same time.

**Comment by kyrofa** [comment]
Sadly that requires a newer cmake than we have in our base, and I haven't investigated what is involved in upgrading bases. I have so little time to maintain this nowadays, I should probably hand it off to snapcrafters.

**Comment by danrobinson78** [comment]
No worries, and I understand the time side. Thanks for the clarification on it.

I'd assume a core bump should be fairly trivial, I know it builds for 20.04 from their OBS repo, but we all know what assuming does and obviously I haven't really tried to build a Snap.

If I also get some spare time I might play with it some but I have no idea when that will be.

**Comment by sergiusens** [comment]
Hi @kyrofa, I don't mind owning the snap if you want.

**Comment by kyrofa** [comment]
Ah then I know it would be in good hands, @sergiusens, thank you. [Let's do it](https://forum.snapcraft.io/t/transfer-darktable-snap/27385).

**Comment by sergiusens** [comment]
@kyrofa don't forget to add me as a collaborator so I can get started and for the transfer to go smoothly :-)

**Comment by sergiusens** [comment]
Just to follow up, I have darktable 3.6.1 for amd64 (tested by myself) and arm64 (untested) on the candidate channel.

I am not sure this is possible for individuals @kyrofa, but if you want we can try and transfer this project to my personal space (sergiusens/darktable-snap) to inherit all the existing issues.

**Comment by kyrofa** [comment]
@sergiusens I can, but you'll need to delete/move your fork first, it whines about the fact that sergiusens/darktable-snap already exists.

**Comment by sergiusens** [comment]
@kyrofa done!

**Comment by kyrofa** [comment]
Okay done, but you'll need to accept the transfer.
