### ISSUE TITLE
(Still) Fails to detect removable media

### ISSUE THREAD

**Issue by RAOF** [sergiusens/darktable-snap#4]
I've installed 2.0.7snap3 (and 2.2.0-rc3-snap2), and connected the removable-media plug, and still removable media don't show up.

**Comment by kyrofa** [comment]
Does the media in question get mounted to /media?

**Comment by RAOF** [comment]
Yes; in /media/chris/CDROM

**Comment by sergiusens** [comment]
If I connect darktable:removable-media on the latest release on stable I can browse and see my importable photos.

I have also requested https://forum.snapcraft.io/t/auto-connect-for-darktable-removable-media/29199, so manually connecting might not need to be necessary in a near future.
