### ISSUE TITLE
Darktable 3.8 is released, please update.

### ISSUE THREAD

**Issue by KristijanZic** [sergiusens/darktable-snap#40]
Please update darktable snap to the latest version.

Here are the release notes:
https://github.com/darktable-org/darktable/releases/tag/release-3.8.0

Please note:
```
The Canon raw CR3 format is now supported (see list of supported cameras in the
section below). This support is provided by LibRaw and requires at least exiv2 version
0.27.4 with BMFF support activated.
```
You'll need to build exiv2 with BMFF support flag enabled.

**Comment by sergiusens** [comment]
I updated 3.8 on candidate, mind testing?

**Comment by sergiusens** [comment]
I also added a command to update the lensfun database

**Comment by sergiusens** [comment]
3.8.1 actually

**Comment by sergiusens** [comment]
Please create new issues, this is also the case for the deb of darktable as seen on this screenshot https://askubuntu.com/questions/1295484/no-maximize-option-available-on-the-title-bar-for-darktable

**Comment by sergiusens** [comment]
3.8.1 is now on stable for amd64 and arm64
