### ISSUE TITLE
Remove or label darktable snap as unmaintaned and depricated.

### ISSUE THREAD

**Issue by KristijanZic** [sergiusens/darktable-snap#42]
Daktable snap seems to just confuse users as it's unmaintained and stuck on an old version and thus it's not even compatible with the current Darktable manual that Darktable points all users to.

The snap should be removed or somehow labeled as unmaintained, maybe rename it to Darktable - depricated so that the user is informed properly as this snap creates more trouble for the users than it actually solves. They keep reporting already fixed bugs, requesting already implemented features, keep getting confused when reading the manual and are not benefiting from the last 6 versions of Daktable. It's currently 3.8 and the snap is still on 3.2.

**Comment by sergiusens** [comment]
I just pushed darktable to canditate, the latest version available

**Comment by sergiusens** [comment]
3.8.1 is now on stable for amd64 and arm64
