### ISSUE TITLE
Darktable 4.2.1 Update

### ISSUE THREAD

**Issue by orthorhombic** [sergiusens/darktable-snap#54]
Please update to the latest darktable release. The new sha256 of the release from 
https://github.com/darktable-org/darktable/releases/ is listed below for convenience. I'm happy to help test. Thank you!

```
$ sha256sum darktable-4.2.1.tar.xz
603a39c6074291a601f7feb16ebb453fd0c5b02a6f5d3c7ab6db612eadc97bac  darktable-4.2.1.tar.xz
```

**Comment by sergiusens** [comment]
thanks, I released 4.2.1 to stable on March 16
